mellanox-hpc/jenkins_scripts

- jenkins/pmix/pmix_jenkins.sh
@miked-mellanox or @Di0gen could you review and merge
> Add tap-formatted output

- jenkins/ompi/ompi_jenkins.sh
@miked-mellanox could you look at this and accept if find one useful
> ompi: Add slurm launching

- jenkins/ompi/ompi_jenkins.sh
Reverts mellanox-hpc/jenkins_scripts#18
> Revert "ompi: Add slurm launching"

- jenkins/ompi/ompi_jenkins.sh
- jenkins/slurm/pmix-slurm-jenkins.sh
@miked-mellanox could you accept one
This test has build release/debug modes, codying style check. Tests will be added later.
> Add script to slurm/pmix verifcation

- jenkins/slurm/pmix-slurm-jenkins.sh
> slurm: Change pmix project location

- jenkins/pmix/pmix_jenkins.sh
- jenkins/slurm/pmix-slurm-jenkins.sh
@miked-mellanox could you review and accept
> Update for slurm and pmix

- jenkins/pmix/pmix_jenkins.sh
@miked-mellanox could you accept
> pmix: Fix script

- jenkins/pmix/pmix_jenkins.sh
- jenkins/slurm/pmix-slurm-jenkins.sh
@miked-mellanox could you accept
> Change libevent location

- jenkins/ompi/ompi_jenkins.sh
@miked-mellanox Can you accept this so I can see why the AMCA file test is failing the mpool_rewrite branch? Once it is isolated the commit can be reverted.
Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>
> Temporary change to amca test

- jenkins/ompi/ompi_jenkins.sh
Addresses https://github.com/open-mpi/ompi/pull/1840
> Possible fix for multithreaded fix

- jenkins/ompi/ompi_jenkins.sh
Addresses https://github.com/open-mpi/ompi/pull/1840
> Possible fix for multithreaded tests n2

- jenkins/ompi/ompi_jenkins.sh
> Increase the timeout to 15m for now. Will need to see why yalla takes

- jenkins/ompi/ompi_jenkins.sh
to ensure that temp files will be cleaned up.
> ompi: Create our own tmpdir for applications

- jenkins/pmix/pmix_jenkins.sh
- Testing with/without dstore
- Fixed test status: the test are fail if one of any tests return a fail code.
> pmix: added testing with and without dstore

- jenkins/pmix/pmix_jenkins.sh
Added opportunity to generate output into files for all clients
and check that all is OK.
> pmix: added check all clients

- jenkins/ompi/ompi_jenkins.sh
Use the one from hpc stack module
> ompi: Disable custom-built UCX master.

- jenkins/pmix/pmix_jenkins.sh
Added:
- key replacement test
- local store test
> pmix: Added tests

- jenkins/pmix/pmix_jenkins.sh
* Enable job fence with direct modex.
> pmix: Enable more PMIx tests

- jenkins/pmix/pmix_jenkins.sh
> pmix: distclean after rpm build

- jenkins/pmix/pmix_jenkins.sh
> pmix: Added the summarized testing output

- jenkins/ompi/ompi_jenkins.sh
Signed-off-by: Jeff Squyres <jeff@squyres.com>
@artpol84 @Di0gen Looks like there's still some more references to the sm BTL that need to be removed (per https://github.com/open-mpi/ompi/pull/3889).
> ompi: remove a few more instances of the sm btl

- jenkins/ompi/ompi_jenkins.sh
Temporally disable it to let OMPI PRs pass.
> Add the feature to disable HCOLL.

- jenkins/ompi/ompi_jenkins.sh
* Respect hcoll enable option
* Properly detect `--timeout` option availability
* Use both external and internal timeout agents
> ompi: Port features from mpi_runner

- jenkins/ompi/ompi_jenkins.sh
Refs https://github.com/open-mpi/ompi/pull/5180
> ompi: disables mtl mxm

- jenkins/ompi/ompi_jenkins.sh
Refs https://github.com/open-mpi/ompi/pull/5192
> ompi: added check for the btl openib is existed

- jenkins/pmix/pmix_jenkins.sh
Refs: https://github.com/pmix/pmix/pull/952
> pmix: fixed checking client's return code

- jenkins/pmix/pmix_jenkins.sh
Signed-off-by: Boris Karasev <karasev.b@gmail.com>
> PMIx 3.1 update

- jenkins/ompi/ompi_test.sh
Signed-off-by: Ralph Castain <rhc@pmix.org>
> Use double-dash on multi-char options

- jenkins/ompi/ompi_test.sh
Signed-off-by: Ralph Castain <rhc@pmix.org>
> Cleanup a couple of more double-dash issues

- jenkins/ompi/ompi_test.sh
Signed-off-by: Ralph Castain <rhc@pmix.org>
> Correct cmd line syntax

- jenkins/ompi/ompi_test.sh
Your example tests routinely demonstrate a left-to-right precedence
ordering when setting the envars. However, one test mistakenly computes
the target sum using right-to-left precedence. I have corrected it in
this PR and provided detailed comments for each test explaining how the
sum is being calculated. This should hopefully help to avoid such
problems in the future.
Signed-off-by: Ralph Castain <rhc@pmix.org>
> Correct an error in the envar sum test

- jenkins/ompi/ompi_test.sh
Signed-off-by: Artem Ryabov <artemry@mellanox.com>
> Disabled thread tests by default (need to revisit them)

- jenkins/ompi/Dockerfile.centos
https://github.com/open-mpi/ompi/pull/7600
> Added pandoc
